# This YAML file must contains the configuration of each mesh to properly build the URDF automagically.
# The aim of this additional file is to encapsulate all the physical properties in a single place without hiding them
# in a long URDF structure.
#
# Note: there is no need to modify this file unless you hack the qbmove physical mechanism. Nonetheless it is
#       recommended to create a distinct YAML file for each version of the qbmove (this helps with versioning and
#       leaves the default configuration as is).
#
# Brief description:
# * The `default` group holds the anchors for the common default settings, i.e. avoid annoying repetitions.
# * The `generictwomotors` group contains the current properties to build the URDF correctly.
# * The `flanges` group holds the anchors for the common settings for the mounting flanges.

default:
  parameters:
    axis: &axis "0 1 0"
    dynamics: &dynamics
      damping: 0.0
      friction: 0.0
    effort_limit: &effort 100
    velocity_limit: &velocity 10000
    limits: &limits
      lower: -15000
      upper: 15000
      effort: *effort
      velocity: *velocity

  motor: &motor
    mesh: ""
    mesh_collision: ""
    position: "0 0 0"
    orientation: "0 0 0"
    axis: *axis
    dynamics: *dynamics
    limits: *limits
    inertial:
      mass: 0.05
      origin: "0.0 0.0 0.025"
      inertia:  # r=0.01m, h=0.05
        ixx: 0.000012
        ixy: 0.0
        ixz: 0.0
        iyy: 0.000012
        iyz: 0.0
        izz: 0.000003


generictwomotors:
  motor_1:
    << : *motor
    position: "0.02 0.02 0.02"

  motor_2:
    << : *motor
    position: "-0.02 -0.02 0.02"